### ISSUE TITLE
Hide passwords

### ISSUE THREAD

**Issue by rclmenezes** [CharterTechChair/Charter-Website#12]
I'm counting two or three passwords you made public. I would change your settings.py to read them from environment variables like:

SECRET_KEY = os.environ.get('SECRET_KEY')
EMAIL_PASSWORD = os.environ.get('EMAIL_PASSWORD')

etc. You can set environment variables in your Heroku setup:
https://devcenter.heroku.com/articles/config-vars

Lastly, you can develop on emails using [Django's email console backend](https://docs.djangoproject.com/en/1.10/topics/email/#console-backend). Turn it on if EMAIL_PASSWORD isn't present in your environment!

Best,

Rodrigo '13

**Comment by wrose100** [comment]
Finally got around to fixing this, thanks!
