### ISSUE TITLE
President and VP fields not updating on contact us page

### ISSUE THREAD

**Issue by wrose100** [CharterTechChair/Charter-Website#2]
On the [contact us page](http://www.princetoncharterclub.org/contactus) the president and vp fields are supposed to update with the current president and vice president objects, but they are still JC and Rory.

**Comment by freddylukai** [comment]
I believe we're not filtering by "is_active"

**Comment by Jasonmk47** [comment]
Yeah, I added a filter to the field. There is a branch out for this now but note that I can't test locally because git is confused when I need to update everything to run this.
